from essentia.standard import TensorflowPredictMusiCNN,TensorflowPredictVGGish, TensorflowPredict2D

embed_models = [
    # A Music embedding extractor based on auto-tagging with the 50 most common tags of the Million Song Dataset, 16000 SR
    dict(name='MSD MusicCNN',
         model_file='msd-musicnn-1.pb',
         algorithm=TensorflowPredictMusiCNN,
         output="model/dense/BiasAdd"),
    # audio embedding extractor trained to predict tags from Youtube videos, 16000 SR
    # dict(name='VGGish',
    #      model_file='audioset-vggish-3.pb',
    #      algorithm=TensorflowPredictVGGish,
    #      output="model/vggish/embeddings"),
]

classifier_models = [
    dict(name='Genre Dortmund MSD MusicCNN Embeddings',
         labels=["alternative","blues","electronic","folkcountr","funksoulrnb","jazz","pop","raphiphop","rock"],
         model_file='genre_dortmund-msd-musicnn-1.pb',
         algorithm=TensorflowPredict2D,
         output="model/Softmax"),
    dict(name='Danceability MSD MusicCNN Embeddings',
         labels=["danceable","not_danceable"],
         model_file='danceability-msd-musicnn-1.pb',
         algorithm=TensorflowPredict2D,
         output="model/Softmax"),
    dict(name='Gender MSD MusicCNN Embeddings',
         labels=["female","male"],
         model_file='gender-msd-musicnn-1.pb',
         algorithm=TensorflowPredict2D,
         output="model/Softmax"),
    dict(name='Mood Acoustic MSD MusicCNN Embeddings',
         labels=["acoustic","non_acoustic"],
         model_file='mood_acoustic-msd-musicnn-1.pb',
         algorithm=TensorflowPredict2D,
         output="model/Softmax"),
    dict(name='Mood Happy MSD MusicCNN Embeddings',
         labels=["happy", "non_happy"],
         model_file='mood_happy-msd-musicnn-1.pb',
         algorithm=TensorflowPredict2D,
         output="model/Softmax"),
    dict(name='Mood Sad MSD MusicCNN Embeddings',
         labels=["non_sad", "sad"],
         model_file='mood_sad-msd-musicnn-1.pb',
         algorithm=TensorflowPredict2D,
         output="model/Softmax"),
    dict(name='Voice Instrumental MSD MusicCNN Embeddings',
         labels=["instrumental","voice"],
         model_file='voice_instrumental-msd-musicnn-1.pb',
         algorithm=TensorflowPredict2D,
         output="model/Softmax"),
    dict(name='Arousal Valence deam MSD MusicCNN Embeddings',
         labels=["valence_deam", "arousal_deam"],
         model_file='deam-msd-musicnn-2.pb',
         algorithm=TensorflowPredict2D,
         output="model/Identity"),
    dict(name='Arousal Valence emomusic MSD MusicCNN Embeddings',
         labels=["valence_emomusic", "arousal_emomusic"],
         model_file='emomusic-msd-musicnn-2.pb',
         algorithm=TensorflowPredict2D,
         output="model/Identity"),
]